-- Isolated Busted environment proof for the ds interaction namespace.

describe('automation helper export', function()
    it('exposes ds without changing the process global table', function()
        assert.is_nil(rawget(_G, 'ds'))
        assert.is_nil(rawget(_G, 'dy'))
        assert.equals(1, ds.protocol_version)
        assert.is_function(ds.await)
        assert.is_function(ds.input)
        assert.is_function(ds.getSaveDirectoryName)
        assert.is_function(ds.mouseWheel)
        assert.is_function(ds.hover)
        assert.is_function(ds.mount)
        assert.is_nil(ds.mount_overlay)
        assert.is_function(ds.move_pointer)
        assert.is_function(ds.root)
        assert.equals('top_left', ds.EScreenOrigin.TOP_LEFT)
        assert.equals('center', ds.EScreenOrigin.CENTER)
        assert.equals('bottom_right', ds.EScreenOrigin.BOTTOM_RIGHT)
    assert.is_function(ds.viewport)
    assert.is_nil(ds.resize)
        assert.is_function(ds.stage_overlay_registration)
        assert.is_function(ds.unmount)
        assert.is_nil(ds.dismiss)
        assert.is_nil(ds.show_fixture)
        assert.is_nil(ds.stage_overlay_fixture)
        assert.is_nil(ds.show_overlay_fixture)
        assert.is_nil(ds.wait_until)
    end)

    it('returns the DFHack directory name of the loaded save game', function()
        assert.equals(dfhack.world.ReadWorldFolder(),
            ds.getSaveDirectoryName())
    end)
end)
